/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_gráfica;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class CadCli extends javax.swing.JFrame {

    /**
     * Creates new form CadCli
     */
    public CadCli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBNOME = new javax.swing.JLabel();
        LBTELEFONE = new javax.swing.JLabel();
        TFNOME = new javax.swing.JTextField();
        TFTELEFONE = new javax.swing.JTextField();
        BTCADASTRAR = new javax.swing.JButton();
        BTLIMPAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBNOME.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBNOME.setText("Nome:");

        LBTELEFONE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBTELEFONE.setText("Telefone:");

        TFNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNOMEActionPerformed(evt);
            }
        });

        BTCADASTRAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTCADASTRAR.setText("Adicionar contato");
        BTCADASTRAR.setToolTipText("");
        BTCADASTRAR.setActionCommand("");
        BTCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCADASTRARActionPerformed(evt);
            }
        });

        BTLIMPAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTLIMPAR.setText("Limpar");
        BTLIMPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLIMPARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(LBNOME)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LBTELEFONE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNOME)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(BTCADASTRAR)
                        .addGap(28, 28, 28)
                        .addComponent(BTLIMPAR)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBNOME)
                    .addComponent(TFNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBTELEFONE)
                    .addComponent(TFTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTLIMPAR)
                    .addComponent(BTCADASTRAR))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNOMEActionPerformed

    private void BTCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCADASTRARActionPerformed
        try {
            String banco = "jdbc:mysql://localhost/agenda telefônica";
            String usuario = "root";
            String senha = "1234";
            Connection conexão = DriverManager.getConnection(banco, usuario, senha);
            Statement comando = conexão.createStatement();
            comando.execute( "insert into contato (nome, telefone) values ('"+TFNOME.getText()+"', '"+TFTELEFONE.getText()+"')");
            JOptionPane.showMessageDialog(null, "Contato adicionado.");
        } catch (SQLException ex) {
            Logger.getLogger(CadCli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTCADASTRARActionPerformed

    private void BTLIMPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLIMPARActionPerformed
        TFNOME.setText("");
        TFTELEFONE.setText("");
    }//GEN-LAST:event_BTLIMPARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCADASTRAR;
    private javax.swing.JButton BTLIMPAR;
    private javax.swing.JLabel LBNOME;
    private javax.swing.JLabel LBTELEFONE;
    private javax.swing.JTextField TFNOME;
    private javax.swing.JTextField TFTELEFONE;
    // End of variables declaration//GEN-END:variables
}
