/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_gráfica;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class Consultacct extends javax.swing.JFrame {

    /**
     * Creates new form Consultacct
     */
    public Consultacct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBCONTATO = new javax.swing.JTable();
        LBNOME = new javax.swing.JLabel();
        TFNOMEBUSCA = new javax.swing.JTextField();
        LBNOME1 = new javax.swing.JLabel();
        TFNOME1 = new javax.swing.JTextField();
        TFTELEFONE = new javax.swing.JTextField();
        BTSALVAR = new javax.swing.JButton();
        BTEXCLUIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        TBCONTATO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Telefone"
            }
        ));
        TBCONTATO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBCONTATOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBCONTATO);

        LBNOME.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBNOME.setText("Nome do contato: ");

        TFNOMEBUSCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNOMEBUSCAActionPerformed(evt);
            }
        });
        TFNOMEBUSCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFNOMEBUSCAKeyReleased(evt);
            }
        });

        LBNOME1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBNOME1.setText("Nome:");

        TFNOME1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNOME1ActionPerformed(evt);
            }
        });

        BTSALVAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTSALVAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_gráfica/floppy-disk.png"))); // NOI18N
        BTSALVAR.setText("Salvar");
        BTSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSALVARActionPerformed(evt);
            }
        });

        BTEXCLUIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTEXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_gráfica/remove.png"))); // NOI18N
        BTEXCLUIR.setText("Excluir contato");
        BTEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEXCLUIRActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_gráfica/phone-call.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TFTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(LBNOME1)
                        .addGap(32, 32, 32)
                        .addComponent(TFNOME1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTSALVAR)
                                .addGap(62, 62, 62)
                                .addComponent(BTEXCLUIR))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(LBNOME)
                                    .addGap(18, 18, 18)
                                    .addComponent(TFNOMEBUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBNOME)
                    .addComponent(TFNOMEBUSCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNOME1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBNOME1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFTELEFONE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTEXCLUIR)
                    .addComponent(BTSALVAR))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNOMEBUSCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNOMEBUSCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNOMEBUSCAActionPerformed

    private void TFNOME1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNOME1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNOME1ActionPerformed

    private void BTSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSALVARActionPerformed
        try {
            String codigo = TBCONTATO.getValueAt(TBCONTATO.getSelectedRow(), 0) .toString();
            String banco = "jdbc:mysql://localhost/agenda telefônica";
            String usuario = "root";
            String senha = "1234";
            Connection conexão = DriverManager.getConnection(banco, usuario, senha);
            Statement comando = conexão.createStatement();
            comando.execute("update contato set nome='"+TFNOME1.getText()+"', telefone='"+ TFTELEFONE.getText() +"' where cod_contato= "+codigo+";");
            JOptionPane.showMessageDialog(null, "Alteração feita com sucesso.");
        } catch (SQLException ex) {
            Logger.getLogger(Consultacct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_BTSALVARActionPerformed

    private void TFNOMEBUSCAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNOMEBUSCAKeyReleased
        try {
            String banco = "jdbc:mysql://localhost/agenda telefônica";
            String usuario = "root";
            String senha = "1234";
            Connection conexão = DriverManager.getConnection(banco, usuario, senha);
            Statement comando = conexão.createStatement();
            try (ResultSet resultado = comando.executeQuery("select * from contato where nome like '"+TFNOMEBUSCA.getText()+"%' order by nome;")) {
                DefaultTableModel model = (DefaultTableModel)  TBCONTATO.getModel();
                model.setNumRows(0);
                while (resultado.next()){
                    model.addRow(new Object[] {resultado.getString("Cod_contato"), resultado.getString("Nome"), resultado.getString("Telefone"),} );
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Consultacct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TFNOMEBUSCAKeyReleased

    private void TBCONTATOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBCONTATOMouseClicked
        String codigo = TBCONTATO.getValueAt(TBCONTATO.getSelectedRow(), 0) .toString();
        
      try {
          String banco = "jdbc:mysql://localhost/agenda telefônica";
            String usuario = "root";
            String senha = "1234";
            Connection conexao = DriverManager.getConnection(banco, usuario, senha);
            PreparedStatement comando = conexao.prepareStatement("Select * from contato where Cod_contato = ?");
            comando.setString(1, codigo);
            ResultSet resultado = comando.executeQuery();
            if (resultado != null && resultado.next()){
            TFNOME1.setText(resultado.getString("Nome"));
            TFTELEFONE.setText(resultado.getString("Telefone"));
            
                
                
            }
            resultado.close();
            
      } catch (SQLException ex) {
            Logger.getLogger(Consultacct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_TBCONTATOMouseClicked

    private void BTEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEXCLUIRActionPerformed
        try {
            String codigo = TBCONTATO.getValueAt(TBCONTATO.getSelectedRow(), 0) .toString();
            String banco = "jdbc:mysql://localhost/agenda telefônica";
            String usuario = "root";
            String senha = "1234";
            Connection conexão = DriverManager.getConnection(banco, usuario, senha);
            Statement comando = conexão.createStatement();
            comando.execute("delete from contato where Cod_contato= " + codigo + ";");
            JOptionPane.showMessageDialog(null, "Contato excluido.");
        } catch (SQLException ex) {
            Logger.getLogger(Consultacct.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BTEXCLUIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultacct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultacct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultacct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultacct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultacct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEXCLUIR;
    private javax.swing.JButton BTSALVAR;
    private javax.swing.JLabel LBNOME;
    private javax.swing.JLabel LBNOME1;
    private javax.swing.JTable TBCONTATO;
    private javax.swing.JTextField TFNOME1;
    private javax.swing.JTextField TFNOMEBUSCA;
    private javax.swing.JTextField TFTELEFONE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
